[tool.poetry]
name = "fastapi_hillel"
version = "0.1.0"
description = ""
authors = ["umterrick <usichenko.vlad67@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.12"
pydantic-settings = "^2.9.1"
sqlalchemy = "^2.0.41"
uvicorn = "^0.34.3"
sqladmin = "^0.20.1"
alembic = "^1.16.2"
psycopg2-binary = "^2.9.10"
python-dotenv = "^1.1.0"
asyncpg = "^0.30.0"
passlib = "^1.7.4"
python-jose = "^3.5.0"
beanie = "^1.30.0"
elasticsearch-dsl = {extras = ["async"], version = "^8.18.0"}
redis = "^6.2.0"
aioredis = "^2.0.1"
aiohttp = "^3.12.13"
kafka-python = "^2.2.15"
pydantic = {extras = ["email"], version = "^2.11.7"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
