"""Add ON DELETE CASCADE for BasketLine.basket_id

Revision ID: 214b24bbcc80
Revises: 668decea37a9
Create Date: 2025-07-28 10:37:55.238063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '214b24bbcc80'
down_revision: Union[str, Sequence[str], None] = '668decea37a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('basket_lines_basket_id_fkey'), 'basket_lines', type_='foreignkey')
    op.create_foreign_key(None, 'basket_lines', 'baskets', ['basket_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'basket_lines', type_='foreignkey')
    op.create_foreign_key(op.f('basket_lines_basket_id_fkey'), 'basket_lines', 'baskets', ['basket_id'], ['id'])
    # ### end Alembic commands ###
