"""Initial migration with Basket and Order models

Revision ID: 2c9f3cc3583c
Revises: 519bd2633dca
Create Date: 2025-07-06 14:48:14.183903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9f3cc3583c'
down_revision: Union[str, Sequence[str], None] = '519bd2633dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
