"""Add ON DELETE CASCADE to OrderLine.order_id

Revision ID: 6ae8137a042a
Revises: 214b24bbcc80
Create Date: 2025-07-30 12:59:07.205613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae8137a042a'
down_revision: Union[str, Sequence[str], None] = '214b24bbcc80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_lines_order_id_fkey'), 'order_lines', type_='foreignkey')
    op.create_foreign_key(None, 'order_lines', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_lines', type_='foreignkey')
    op.create_foreign_key(op.f('order_lines_order_id_fkey'), 'order_lines', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
